proto_library(
    name = "my_service_proto",
    srcs = ["myservice.proto"],
    visibility = ["//visibility:public"],
)

proto_library(
    name = "my_service_proto_scalajs",
    srcs = ["myservice.proto"],
    visibility = ["//visibility:public"],
)
