load("@io_bazel_rules_scala//scala:scala_import.bzl", "scala_import")

scala_import(
    name = "scalajs_compiler",
    jars = [
        "scalajs-compiler_2.12.8-1.5.0.jar",
    ],
    visibility = ["//visibility:public"],
    #    exports = [
    #        "//3rdparty/jvm/org/scala_js:scalajs_library",
    #    ],
)
